### ISSUE TITLE
Application crash editing text labels

### ISSUE THREAD

**Issue by adripanico** [PrevasVST/SubstationRISE#11]
When editing the SLD, if you add a text label and try to edit it, application crash.

This screenshot is coming from my side:
![error2](https://cloud.githubusercontent.com/assets/467658/11035968/d88f477e-86f5-11e5-800f-34b0e9e764ea.PNG)

And this one is coming from other user:
![error](https://cloud.githubusercontent.com/assets/467658/11035930/ab8dbce2-86f5-11e5-8be8-f16582d7f9ec.PNG)

**Comment by andreykruglyak** [comment]
Same as issue #9. Fixed in version 1.0.0.30.
