### ISSUE TITLE
Recommendations not shown

### ISSUE THREAD

**Issue by adripanico** [PrevasVST/SubstationRISE#12]
Problem remains with recommendations not appearing for a selected component:

![recommenda](https://cloud.githubusercontent.com/assets/467658/11064069/0809d4f4-87bb-11e5-9a06-d7a307bd86ca.PNG)

**Comment by andreykruglyak** [comment]
Problem for non-ABB components. TODO: check default recommendations, check matching rules.

May be related to the problem where some recommendations for all models should be applied to both ABB and non-ABB components.

**Comment by andreykruglyak** [comment]
Fixed in 1.1.0.3.
