### ISSUE TITLE
LCC/year calculation

### ISSUE THREAD

**Issue by adripanico** [PrevasVST/SubstationRISE#15]
There are some wrong behaviour with the calculation of LCC/year:
![ls1](https://cloud.githubusercontent.com/assets/467658/11066448/8b6b1120-87c8-11e5-875d-8b697943bbbb.png)

**Comment by andreykruglyak** [comment]
Check project life for this alternative.

**Comment by adripanico** [comment]
Where is that field? Project life is not defined for the whole project?

**Comment by andreykruglyak** [comment]
One of the parameters in selecting optimal solution view. Project life or project life cycle, something similar.

**Comment by adripanico** [comment]
You are right, I was looking into Evaluation of potential alternatives step.

I proceed to close this issue then.
