### ISSUE TITLE
Comparison criteria charts - Alternatives' names

### ISSUE THREAD

**Issue by adripanico** [PrevasVST/SubstationRISE#16]
In some graphs #N appears instead of the real alternative name:

![ls2](https://cloud.githubusercontent.com/assets/467658/11066510/d062cc0a-87c8-11e5-82b8-adf52f695e97.png)

**Comment by andreykruglyak** [comment]
This is necessary for views with data for individual loads, since there is very little space.

**Comment by adripanico** [comment]
It appears as Alt 1 in the first graph and then as #2 in the second one. This is impossible to understand by the user or the report readers.

**Comment by andreykruglyak** [comment]
#1 refers to "Technical solution #1" - see the picture above - and I think this is consistent with the original requirements. The name "Alt 1" just happens to be short in this example, it can be very long and will have no place in the graph.
