### ISSUE TITLE
Duplicate keyword into translation module

### ISSUE THREAD

**Issue by adripanico** [PrevasVST/SubstationRISE#2]
**Translation module > Maintenance reports > Substation Risk Analysis**

In translation module, working with Substation Risk Analysis document for Maintenance reports, *Designation* appears twice:

![translation](https://cloud.githubusercontent.com/assets/467658/10541196/6e4e3d50-740f-11e5-8fe2-d2b827def280.PNG)

**Comment by andreykruglyak** [comment]
Has to be fixed in the DB (duplicate entries).

**Comment by andreykruglyak** [comment]
Fixed in 1.1.0.3.
