### ISSUE TITLE
Bug in translation module

### ISSUE THREAD

**Issue by adripanico** [PrevasVST/SubstationRISE#22]
While translating the reports, after enter the translated text, the corresponding original text is changed to the translated one:

![translation](https://cloud.githubusercontent.com/assets/467658/11710402/252f56be-9f1f-11e5-8140-05c7ed7583ee.PNG)

**Comment by andreykruglyak** [comment]
This is critical and will be fixed urgently. I will also restore the original English translations.

Best regards,
Andrey
______________________________
Andrey Kruglyak, Consultant, Prevas AB
Box 4, SE-721 03 Västerås, Sweden
Visit: Legeringsgatan 18
Mobile: +46 (0)70 616 76 03
Switchboard: +46 (0)21 360 19 00
andrey.kruglyak@prevas.se<mailto:andrey.kruglyak@prevas.se>
www.prevas.se<http://www.prevas.se/>


[cid:C1DB4BBA-E146-4269-B5CE-D38F55CD5D4A@prevas.se]


Innovation for Growth

On 10 Dec 2015, at 09:19, Ardi Knight <notifications@github.com<mailto:notifications@github.com>> wrote:


While translating the reports, after enter the translated text, the corresponding original text is changed to the translated one:

[translation]<https://cloud.githubusercontent.com/assets/467658/11710402/252f56be-9f1f-11e5-8140-05c7ed7583ee.PNG>

**Comment by andreykruglyak** [comment]
Fixed in 1.1.0.8.
