### ISSUE TITLE
Wrong tooltip for fuses and power supplies

### ISSUE THREAD

**Issue by adripanico** [PrevasVST/SubstationRISE#29]
Fuses and power supplies show "Closed" tooltip when mouse is over:

![2015-12-11 12_51_20-](https://cloud.githubusercontent.com/assets/467658/11743271/873258ec-a006-11e5-9095-063fab2333c5.png)

**Comment by andreykruglyak** [comment]
That is correct since they are switches and can be open. Simulate e.g. clear fault to see that.
