### ISSUE TITLE
Special characters into reports

### ISSUE THREAD

**Issue by adripanico** [PrevasVST/SubstationRISE#3]
**Customer / Installation info -> reports**

Although special characters seem to work fine for translations, conclusions, etc., there are some fields like customer and installation names that represent those special characters into the software but not into the generated reports.

![textos_nordicos2](https://cloud.githubusercontent.com/assets/467658/10575758/f90529c6-765e-11e5-99cf-8e1936d50244.png)

**Comment by andreykruglyak** [comment]
Fixed in 1.1.0.11.
