### ISSUE TITLE
Classification on Assessment conclusions

### ISSUE THREAD

**Issue by adripanico** [PrevasVST/SubstationRISE#31]
According to the mock-up, "Executive summary" section is correctly placed, but "Assessment report" section is missing.

![untitled](https://cloud.githubusercontent.com/assets/467658/11813342/48b8970a-a341-11e5-9a98-8d132a7f4523.png)

In any case, better than adding a new static text that may lead to confussion, I think it is better to remove the "Executive Summary" title (change it by the name of the step, as in the rest of steps).

![a](https://cloud.githubusercontent.com/assets/467658/11813434/cf306a74-a341-11e5-9869-fd57bc3f72a1.png)

**Comment by andreykruglyak** [comment]
Fixed in 1.1.0.9.
