### ISSUE TITLE
Application freeze and crash importing a configuration (XML)

### ISSUE THREAD

**Issue by adripanico** [PrevasVST/SubstationRISE#34]
To try to replicate exactly what I did with the project you say is corrupted, I have a SLD exported since it is a simple layout for testing. So, a new project I’ve imported such SLD. The components appear fine, but when I click next, “Calculating importance and risk” appears during a while and then the application crash. I’ve tested it three times with the same result:

![crash](https://cloud.githubusercontent.com/assets/467658/11871681/57125ca0-a4d1-11e5-92f7-8f7fd67fff0e.jpg)

Files sent on Dec 16.

**Comment by andreykruglyak** [comment]
Where do you export the SLD from? From the corrupted project? 
It is correct that the data in the exported SLD is corrupted as well, I've verified that.
