### ISSUE TITLE
Unable to generate Maintenance and O&M reports

### ISSUE THREAD

**Issue by adripanico** [PrevasVST/SubstationRISE#35]
I am unable to generate reports for Maintenance and Operation&Maintenance. In both cases, application doesn’t crash, but the report is not being generated.

The error:
![aa](https://cloud.githubusercontent.com/assets/467658/12233413/646c5244-b867-11e5-81db-dce9f043f032.png)

Related project files sent 2016/01/11.

Assessment and LifeStretch generate the reports correctly.

**Comment by andreykruglyak** [comment]
Fixed in DB.
