### ISSUE TITLE
Empty fields in recommendations

### ISSUE THREAD

**Issue by adripanico** [PrevasVST/SubstationRISE#7]
The user is able to write a non-complete recommendation into the software, but then report generation fails:

![capture](https://cloud.githubusercontent.com/assets/467658/10663196/e821358e-78b9-11e5-9ec3-705928e456a5.PNG)

![capture2](https://cloud.githubusercontent.com/assets/467658/10663199/ea92ae74-78b9-11e5-80b4-3d8191bc6c25.PNG)

**Comment by andreykruglyak** [comment]
Fixed in 1.0.0.31.
