### ISSUE TITLE
String was not recognized as a valid DateTime

### ISSUE THREAD

**Issue by adripanico** [PrevasVST/SubstationRISE#8]
Error through when importing a project from tablet app to desktop application.

Neither assessed components nor taken photos are imported.

Project files sent in separate email (2015-10-26).

![capture](https://cloud.githubusercontent.com/assets/467658/10725307/61a7d34a-7bcb-11e5-8ff0-c8a5f364b817.PNG)

**Comment by andreykruglyak** [comment]
Cannot replicate but probably fixed in version 1.0.0.30.

**Comment by andreykruglyak** [comment]
Cannot replicate but confirmed by Adrian on his PC with version 1.0.0.32.

**Comment by andreykruglyak** [comment]
In version 1.1.0.0: setting photo date to today if cannot parse during import, displaying a more explicit error message for future debugging.

**Comment by andreykruglyak** [comment]
Fixed in 1.1.0.3.
